name: el_comparison
description: "A project to compare different localization approaches"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+2
  intl: ^0.19.0
  dio: ^5.7.0

  # @ "Default localization approach"
  flutter_localizations:
    sdk: flutter

  # @ Easiest localization
  easiest_localization:
    path: ../locy
  easiest_remote_localization:
    path: ../el_localizely
  localization:
    path: ./localization

  # @ Easy localization
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/i18n/easy/
    - assets/i18n/easy_json/
    - assets/i18n/easiest/
    - assets/i18n/flutter_localizations/


localization:
  arb-dir: ./assets/i18n/flutter_localizations/
  template-arb-file: app_en.arb
  output-dir: ./lib/flutter_localizations/
  output-localization-file: flutter_localizations.dart
  use-named-parameters: true

easiest_localization:
  excluded:
    - "/easy/"
    - "/flutter_localizations/"
    - "/easy_json/"
    - "fr.json"
  class_name: LocalizationMessages
  description: Generated localization package
  easiest_localization_version: "\n    path: ../../locy"
  package_name: localization
  package_path: './'
  primary_localization: "en"
  format_output: true
  save_merged_files: true