name: el_comparison
description: "A project to compare different localization approaches"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # @ Easiest localization
  easiest_localization:
    path: ../locy
  easiest_remote_localization:
    path: ../el_localizely
  localization:
    path: ./localization

  # @ Easy localization
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/i18n/easy/
    - assets/i18n/easiest/

easiest_localization:
  excluded:
    - "/easy/"
  class_name: LocalizationMessages
  description: Generated localization package
  easiest_localization_version: "\n    path: ../../locy"
  package_name: localization
  package_path: './'
  primary_localization: "en"
  format_output: true
  save_merged_files: true